name: api_client
description: Rest Client.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  app_core:
    path: ../app_core
  dio: ^5.7.0
  flutter:
    sdk: flutter
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  todo_repository:
    path: ../todo_repository
  user_repository:
    path: ../user_repository






dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=8.0.0 <10.0.0'

  very_good_analysis: ^5.1.0