name: task_manger_app
description: "Task Manager App Using Flutter That Allows Users To Manage Their Tasks Efficiently."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  api_client:
    path: packages/api_client
  app_core:
    path: packages/app_core
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6

  go_router: ^14.6.1
  user_repository:
    path: packages/user_repository




dev_dependencies:
  flutter_test:
    sdk: flutter


  very_good_analysis: ^5.1.0


flutter:

  uses-material-design: true


fonts:
  - family: Cera Pro
    fonts:
      - asset: assets/fonts/Cera-Pro/Cera-Pro-Medium.otf
      - asset: assets/fonts/Cera-Pro/Cera-Pro-Bold.otf