name: app_core
description: Core app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3


dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.0
  very_good_analysis: ^5.1.0